Ns 162/dto for total http requests
net-stalker/net-api pull request #28
Opened 2024-03-05 14:53 UTC by net-illia-stetsenko

Implemented api for total http requests chart

2024-03-05 14:54 UTC, net-illia-stetsenko commented
Also deleted unused dashboard api

2024-03-06 13:32 UTC, net-yehor-tretiakov commented on net-reporter-api/src/api/total_http_requests/total_http_requests_filters.rs
> +    pub fn is_include_http_methods_mode(&self) -> Option<bool> {
There might be a conversation about if we should name returning `Option<T>` methods `is_..`

2024-03-06 13:32 UTC, net-yehor-tretiakov commented on net-reporter-api/src/api/total_http_requests/total_http_requests.rs
> +    fn reader_correctly_read_encoded_graph_edge() {
`..._graph_edge` COPIUM

2024-03-06 13:33 UTC, net-yehor-tretiakov commented on net-reporter-api/src/api/total_http_requests/total_http_requests_filters.rs
> +    fn reader_correctly_read_encoded_nbpe_filters_0() {
I hate adding numbers here (in the names)

2024-03-06 13:34 UTC, net-yehor-tretiakov commented on net-reporter-api/src/api/total_http_requests/http_requests_bucket.rs
> +    fn reader_correctly_read_encoded_bandwidth_bucket() {
Yeap, no ctrl+C 4sure

2024-03-06 13:34 UTC, net-yehor-tretiakov requested changes
Get rig of all the ctrl+C (naming) issues

2024-03-06 15:06 UTC, merged